Doc update
ufs-community/ufs-mrweather-app pull request #187
Opened 2020-09-04 20:42 UTC by panll

Changed parts:
1) UPP related parts (4.2.3, and 7.11)
2) initial condition file name changes (4.3.3, and 4.3.8)

2020-09-04 22:46 UTC, ligiabernardet requested changes
Thank you @panll for your work in documenting the multiple changing aspects of this App. And for documenting code that is still hot off the oven. Overall looks great, various comments below. Have a restful weekend!

- All file and directory names should be enclosed in double back quotes.
- Refer to the App as MR Weather App (no UFS ahead of it) for consistency throughout document.

- This blurb is a repeat from Table 2.1 and should be removed
```
Hera and Cheyenne are preconfigured platforms and the static files and prestaged intial conditons can be found at the followind directories:
.. code-block:: console	.. code-block:: console
   Hera: /scratch1/NCEPDEV/stmp2/CIME_UFS	   Hera: /scratch1/NCEPDEV/stmp2/CIME_UFS
   Cheyenne: /glade/p/cesmdata/cseg/ 	   Cheyenne: /glade/p/cesmdata/cseg/ 
```

- Files in NEMSIO and GRIB2 _format_ (singular)
- resolutions of 0.5, or 1.0 degree -> resolutions of 0.5 and 1.0 degree
- in 0.25 , 0.50, or 1.0 degree grid spacing -> in 0.50 or 1.0 degree grid spacing
- Section 4.3.2: Must refer user to both current and historic sources of GRIB2 data (refer to our raw ICs Google Doc cheat sheet)
- After sentence _The default naming convention for the initial condition files is described below,_ add The user must stage the files on disk following this convention so they can be recognized by the MR Weather App workflow.
- In a couple of places it says that the default ICs for the Dorian case are pre-staged in preconfigured platforms. That is true on Cheyenne and Hera but not on Jet and Gaea. I will ask Dom if we can stage them on Jet and Gaea as well. If that happens, the documentation is correct. If not, need to update.
- If users want to run the UFS MR Weather App with initial conditions other than 0.5 deg GRIB2 data available through NOMADS -> If users want to run the UFS MR Weather App with initial conditions other than what is centrally available in preconfigured platforms
- Directory $DIN_LOC_IC/YYMMMM/YYYYMMDD can have both GRIB2 and NEMSIO files -> Directory $DIN_LOC_IC/YYMMMM/YYYYMMDD can have GRIB2, NEMSIO, and netCDF files
- Python = 2.7 -> 2.7 or 3

2020-09-04 22:46 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
> +  - Surface variables and atmosphere state in 0.5 deg ``atm.input.ic.grb2``
It is not just for 0.5 deg. This is the naming convention for any GRIB2 file.
```suggestion
  - Surface variables and atmosphere state ``atm.input.ic.grb2``
```

2020-09-04 22:46 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
> +From v1.1.0, the data need to be downloaded mannually if the intial conditions are not avavilable in ``$DIN_LOC_IC``.
```suggestion
Starting with the v1.1.0 release, the MR Weather App workflow no longer auto-downloads datasets. The data must be present in the centralized location (for preconfigured platforms) or downloaded manually.
```
The following 2 sections (About the automatic stating of initial conditions by CIME) needs to be removed.

2020-09-04 22:46 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
>           wget -c https://www.ncei.noaa.gov/thredds/catalog/model-gfs-g3-anl-files/$yyyymmdd/gfs_3_${yyyymmdd}_${hh}00_000.grb2
Need to explain about current and old files - they are available in different locations and naming conventions vary.
What is the best way to do that? A table of file names and sources?

2020-09-04 22:46 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
>    If the user is initializing from 1.0-degree :term:`GRIB2` format data, which on
This is no longer needed. The user can put a 0.5 deg or 1.0 deg file on disk, call it atm.input.ic.grb2, and the App and chgres_cube will process it properly regardless of whether it is a 0.5 or 1.0 deg file

2020-09-04 23:12 UTC, panll commented
Thanks, Ligia! I'll modify the file accordingly. @ligiabernardet

2020-09-08 14:53 UTC, ligiabernardet commented
Tks for the updates. Please let us know when this is ready to review again.

2020-09-08 15:01 UTC, panll commented
Sure, thanks! @ligiabernardet

2020-09-08 19:22 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +Documentation for the Unified Post Processor (UPP) output files can be found `here <https://upp.readthedocs.io/en/ufs-v1.1.0/InputsOutputs.html>`_.
Changed, thanks!

2020-09-08 19:25 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +Customizing UPP output files for the MR Weather App
Updated. Thanks!

2020-09-08 19:29 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +If you wish to modify the fields or levels that are output from the Unified Post Processor, you will need to make modifications to files postcntrl_gfs_f00.xml (used to post-process model data at the
Updated. Thanks!

2020-09-08 19:32 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +  - Surface variables and atmosphere state in 0.5 deg ``atm.input.ic.grb2``
Changed!

2020-09-08 19:40 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +From v1.1.0, the data need to be downloaded mannually if the intial conditions are not avavilable in ``$DIN_LOC_IC``.
Changed.

2020-09-08 19:43 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>    If the user is initializing from 1.0-degree :term:`GRIB2` format data, which on
Removed.

2020-09-08 20:20 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>           wget -c https://www.ncei.noaa.gov/thredds/catalog/model-gfs-g3-anl-files/$yyyymmdd/gfs_3_${yyyymmdd}_${hh}00_000.grb2
Actually, there is a website listing all the data source: https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs

2020-09-12 15:49 UTC, ligiabernardet requested changes
I have not had time to go through the entire document yet. So this is a review in progress.

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/repos_and_directories.rst
> +   | the MR Weather App        |                                                         |
This table is not showing in the resulting HTML. I am not sure why. It could be that when you replaced UFS with MR the line got shorter and the misalignment made the table not be processed. Needs to be fixed.

Add a line with UPP -> https://github.com/NOAA-EMC/EMC_post

Right below the Note in Blue, add a second, separate, note in blue with: 
The UPP is included in the MR Weather App code for the sole purpose of facilitating customization of the fields to be post-processed. The code and executable for running UPP are part of the NCEPLIBS.

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/introduction.rst
> +The first of these to be released to the community is the Medium-Range
We need UFS here as we are now defining that the UFS Medium-Range Weather Application will later on be referred to as the MR Weather App.
```suggestion
The first of these to be released to the community is UFS the Medium-Range
```

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
>  (`GRIB2 <https://www.nco.ncep.noaa.gov/pmb/docs/grib2/>`_,
Rephrase. CIME cannot automatically retrieve files.

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
>  <https://ufs-weather-model.readthedocs.io/en/ufs-v1.0.0>`_.
Version needs to change to 1.1.0 - link should work

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
> +The GFS data can be provided in three formats: :term:`NEMSIO`, :term:`netCDF`, or :term:`GRIB2`. Files in NEMSIO and GRIB2 format can be obtained
Remove the sentence: Files in ...
The websites for obtaining the data are described right below.

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
> +  These files cover the entire globe and resolutions of 0.5 and 1.0 degree are supported. There are both current and historic sources of GRIB2 `data available <https://docs.google.com/document/d/1rmQ
Pls remove mention to this Google Doc - all necessary information should be in this User's Guide. I apologize if I was misleading with previous guidance when I recommended that you referred to the Google Doc. I meant you should refer to it when writing the User's Guide.

2020-09-12 15:49 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
Provide users with 4 locations of files:

- 0.5 deg current
- 0.5 deg historic
- 1.0 deg current
- 1.0 deg historic

-

2020-09-12 18:36 UTC, panll commented
Thanks, Ligia! I'll modify the document accordingly.

2020-09-13 03:26 UTC, ligiabernardet requested changes
Thanks for the updates. I have completed teh review and noted a few more changes that are needed.

Pls remove FAQ question _7.15. How to change the filenames for input to chgres_cube?_
In the latest code, the app will only recognize files with the agreed-upon naming convention (sfc.input.ic.* and atm.input.ic.*). A user cannot use a file called gfs*.

For this PR, no changes needed in FAQ _How can I change number of task used by chgres_cube or UPP (NCEP-Post)?_. But before the release, need to check this FAQ to see if changes are needed.

2020-09-13 03:26 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
> +  These files cover the entire globe and resolutions of 0.5 and 1.0 degree are supported. There are both current and historic sources of GRIB2 `data available <https://docs.google.com/document/d/1rmQ
Also add: At the time of this writing, files for dates 05/15/2020 12 UTC or more recent are considered current, while files for preceding dates are considered historical. However, the cutoff date may change in the future.

2020-09-15 15:09 UTC, ligiabernardet commented
@panll Please let me know when you are done making the changes so I can review again. Thanks.

2020-09-15 15:24 UTC, panll commented
Yes, thanks! I'll try to finish it today. @ligiabernardet

2020-09-15 23:59 UTC, panll commented on docs/UsersGuide/source/repos_and_directories.rst
> +   | the MR Weather App        |                                                         |
Changed, thanks!

2020-09-16 00:00 UTC, panll commented on docs/UsersGuide/source/introduction.rst
> +The first of these to be released to the community is the Medium-Range
Changed!

2020-09-16 00:00 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>  (`GRIB2 <https://www.nco.ncep.noaa.gov/pmb/docs/grib2/>`_,
Changed.

2020-09-16 00:00 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>  <https://ufs-weather-model.readthedocs.io/en/ufs-v1.0.0>`_.
Changed.

2020-09-16 00:02 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +The GFS data can be provided in three formats: :term:`NEMSIO`, :term:`netCDF`, or :term:`GRIB2`. Files in NEMSIO and GRIB2 format can be obtained
Changed.

2020-09-16 00:03 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +  These files cover the entire globe and resolutions of 0.5 and 1.0 degree are supported. There are both current and historic sources of GRIB2 `data available <https://docs.google.com/document/d/1rmQ
Added, thanks!

2020-09-16 00:04 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
Added.

2020-09-16 00:07 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
> +Starting with the v1.1.0 release, the MR Weather App workflow no longer auot-downloads datasets. The data must be present in the centralized location (for preconfigured platforms) or downloaded manua
Changed.

2020-09-16 00:09 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>  Staging initial conditions manually using CIME
Deleted.

2020-09-16 00:10 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>       For downloading files in GRIB2 format with 0.5 degree grid spacing, the same code ``get.sh`` can be used except the wget command should be replaced with the following line:
Changed.

2020-09-16 00:23 UTC, panll commented
The documentation is updated and ready to review, and please let me know if something is missing, thanks! @ligiabernardet

2020-09-16 15:41 UTC, ligiabernardet requested changes
Looking good! Just found one typo.

Also, to address [https://github.com/ufs-community/ufs-mrweather-app/issues/163](https://github.com/ufs-community/ufs-mrweather-app/issues/163), please change the Quick Start chapter, from  _The following quick start guide is applicable to versions of the Medium-Range Weather Application that are on preconfigured or configurable machines as listed here._, to: _The following quick start guide is applicable to versions of the MR Weather App that are on preconfigured machines as listed here. For other machines, please refer to Chapter 5 before using the quick start guide._ 
When referring to Chapter 5, use internal link (do not hardcode to 5).

2020-09-16 15:41 UTC, ligiabernardet commented on docs/UsersGuide/source/inputs_outputs.rst
>    - 1.0 deg hidtorical files can be requested from `<https://www.ncei.noaa.gov/thredds/catalog/model-gfs-g3-anl-files-old/catalog.html>`_
```suggestion
  - 1.0 deg historical files can be requested from `<https://www.ncei.noaa.gov/thredds/catalog/model-gfs-g3-anl-files-old/catalog.html>`_
```

2020-09-16 17:28 UTC, panll commented on docs/UsersGuide/source/inputs_outputs.rst
>    - 1.0 deg hidtorical files can be requested from `<https://www.ncei.noaa.gov/thredds/catalog/model-gfs-g3-anl-files-old/catalog.html>`_
Changed, thanks!

2020-09-16 18:53 UTC, panll commented
Changed, thanks!

2020-09-17 17:05 UTC, ligiabernardet approved these changes

2020-09-17 17:14 UTC, merged