Doc update
ufs-community/ufs-mrweather-app pull request #203
Opened 2020-09-24 16:18 UTC by panll

Update section 6 for regression testing.

2020-09-25 00:23 UTC, ligiabernardet requested changes

2020-09-25 00:23 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +In order to run the tests, NCEPLIB and NCEPLIBS-external need to be installed (see :numref:`Chapter %s <config_new_platform>` for instructions). These libraries have been preinstalled on Cheyenne, bu
```suggestion
In order to run the tests, NCEPLIBS and NCEPLIBS-external need to be installed (see :numref:`Chapter %s <config_new_platform>` for instructions). These libraries have been preinstalled on Cheyenne, but not on Stampede and Orion.
```

2020-09-25 00:23 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +The input data needed for the tests are staged on preconfigured machine Cheyenne. On Orion and Stampede, data must be acquired from the ftp site and staged on disk (see :numref:`Chapter %s <inputs_an
We are going to need more specific instructions here. I will provide a suggestion separately.

```suggestion
The input data needed for the tests needs to be on disk before the tests are submitted. It is already staged on Cheyenne since it is a preconfigured platform. On Orion and Stampede, data must be acquired from the ftp site and staged on disk (see :numref:`Chapter %s <inputs_and_outputs>`) before proceeding with the test. Then setting the running environment according to :numref:`Chapter %s <quickstart>`. 
```

2020-09-25 00:23 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
>  To run a Smoke startup test::
```suggestion
To run a SMS test::
```

2020-09-25 00:23 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +Here are the commands to run RT on Cheyenne, Orion, and Stampde::
```suggestion
The commands to run the regression test on Cheyenne, Orion, and Stampede are below. You must replace the compute projects listed (using variable ``PROJECT``) to a project you can use to run the tests. ::
```
There should not be words inside the code blocks, only commands. So please separate this blurb in three parts, with three code blocks.

Explain why there are 3 sets for Stampede. And that the 3 sets of RTs need to be submitted separately on Stampede, that is, only submit the second set once the 1st is done, and only submit the 3rd once the 2nd is done.

2020-09-25 00:23 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
>  **$CIMEROOT/scripts/query_testlists** gathers descriptions of the tests and testlists available
Need to define testlists.

2020-09-25 02:58 UTC, panll commented
Thanks, Ligia! I'll modify the document accordingly.

2020-09-25 14:23 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +There are around 38 test cases available for the regression testing to ensure the system is installed correctly and works properly. The regression testing (RT) also makes sure that new code upgrades
Changed, thanks!

2020-09-25 14:23 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +`create_test <https://esmci.github.io/cime/versions/ufs_release_v1.1/html/Tools_user/create_test.html>`_ is the CIME tool used to do the RT.
Changed, thanks!

2020-09-25 14:24 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +In order to run the tests, NCEPLIB and NCEPLIBS-external need to be installed (see :numref:`Chapter %s <config_new_platform>` for instructions). These libraries have been preinstalled on Cheyenne, bu
Changed, thanks!

2020-09-25 14:27 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +The input data needed for the tests are staged on preconfigured machine Cheyenne. On Orion and Stampede, data must be acquired from the ftp site and staged on disk (see :numref:`Chapter %s <inputs_an
Changed.

2020-09-25 14:28 UTC, panll commented on docs/UsersGuide/source/testing.rst
>  To run a Smoke startup test::
Changed, thanks!

2020-09-25 15:53 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +Here are the commands to run RT on Cheyenne, Orion, and Stampde::
Added, thanks!

2020-09-25 15:54 UTC, panll commented on docs/UsersGuide/source/testing.rst
>  **$CIMEROOT/scripts/query_testlists** gathers descriptions of the tests and testlists available
Added the testlist for Cheyenne, thanks!

2020-09-25 16:56 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +Pre-existing baselines are not provided for this App. Users can run the tests without using a baseline (just to certify that the tests run to completeion) or create their own baseline (to compare fut
```suggestion
Pre-existing baselines are not provided for this App. Users can run the tests without using a baseline (just to certify that the tests run to completion) or create their own baseline (to compare future runs against).
```

2020-09-25 16:58 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +The input data needed for the tests needs to be on disk before the tests are submitted. It is already staged on Cheyenne since it is a preconfigured platform. On Orion and Stampede, data must be acqu
Avoid the word need twice in same sentence
```suggestion
The input data required for the tests needs to be on disk before the tests are submitted. It is already staged on Cheyenne since it is a preconfigured platform. On Orion and Stampede, data must be acquired from the ftp site and staged on disk (see :numref:`Chapter %s <inputs_and_outputs>`) before proceeding with the test. Then setting the running environment according to :numref:`Chapter %s <quickstart>`. 
```

2020-09-25 17:28 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +for UFS, the components, and projects. The available testlists for Cheyenne: ::
```suggestion
for UFS, the components, and projects. The available tests for Cheyenne are: ::
```
After the green box, explain what testlists are. For example: The results indicate that there are tests available on Cheyenne for two compilers (Intel and GNU). Furthermore, the results indicate that all tests are part of a ``testlist`` called  _prealpha_. ``Testlists`` are lists that aggregate a number of tests under a single umbrella. All tests contained in a ``testlist`` can be run with single command when the ``testlist`` is passed as an argument to the ``create_test`` command.

2020-09-25 20:12 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +Pre-existing baselines are not provided for this App. Users can run the tests without using a baseline (just to certify that the tests run to completeion) or create their own baseline (to compare fut
Changed, thanks!

2020-09-25 20:12 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +The input data needed for the tests needs to be on disk before the tests are submitted. It is already staged on Cheyenne since it is a preconfigured platform. On Orion and Stampede, data must be acqu
Changed.

2020-09-25 20:12 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +for UFS, the components, and projects. The available testlists for Cheyenne: ::
Changed.

2020-09-25 21:09 UTC, panll commented
The section 6 is updated with Ligia's draft. Please let me know if i missed something. @ligiabernardet

2020-09-25 23:24 UTC, ligiabernardet requested changes
It seems tat part of the draft in the Google Doc did not end up in the final document. I am referring to:
 
Several environment variables need to be set before running the regression tests. The instructions below provide quick information on how to set up the environment variables (for complete information, users should refer to Chapter 2).

export myUFS_INPUT=my_directory	# Directory for staging input datasets
export UFS_SCRATCH=my_scratch_space  # Directory for output files
export PROJECT=your_compute_project 	# Project you can use to conduct runs in your platform
export UFS_DRIVER=nems		# Do not change
export CIME_MODEL=ufs			# Do not change

2020-09-25 23:27 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +Here are the commands to run RT on Cheyenne, Orion, and Stampde::
There should not be words inside the code blocks, only commands. So please separate this blurb in three parts, with three code blocks, one for each platform.

2020-09-25 23:35 UTC, ligiabernardet commented on docs/UsersGuide/source/testing.rst
> +Here are the commands to run RT on Cheyenne, Orion, and Stampde::
Explain why there are 3 sets for Stampede and that the 3 sets of RTs need to be submitted separately on Stampede, For example: 
On Stampede it is necessary to submit the tests divided in three ``testlists`` (_prealpha_p1_, _pre_alpha_p2_, and _prealpha_p3_ because there is a limit to the number of jobs a user can have in the queue at a given time. Users should submit each set of tests separately, and wait for all tests to finish before submitting the next set.

2020-09-25 23:38 UTC, panll commented
Sorry, the missed part should be in now. Thanks! @ligiabernardet

2020-09-26 00:02 UTC, panll commented on docs/UsersGuide/source/testing.rst
> +Here are the commands to run RT on Cheyenne, Orion, and Stampde::
Changed, thanks!

2020-09-27 20:14 UTC, ligiabernardet approved these changes
Looks good, ready to merge.

2020-09-28 02:10 UTC, climbfuji approved these changes

2020-09-28 02:10 UTC, merged