To merge in global-workflow build option
ufs-community/ufs-mrweather-app pull request #230
Opened 2022-04-18 16:22 UTC by jkbk2004

This is initial PR to provide the global-workflow capability in the ufs-mrweather-app repo. 

1. A shell script is added to check out and build global-workflow. 
2. Basic instructions are given in README.
3. Tested ok on hera until generating rocoto xml file to set forecast experiment.
4. Detail steps to launch out the forecast experiment will be followed in next PRs.

2022-04-28 14:50 UTC, ulmononian approved these changes
Builds successfully on Hera and Orion. Case build/set-up functional using arbitrary C384, coupled ATM test; rocoto XML & Cron files generate successfully.

2022-04-29 00:11 UTC, ligiabernardet requested changes
I can't see a reason for keeping file Externals.cfg.v1.0 in the repo. If someone needs to know what Externals.cfg looked like for the v1 release, they can look at the v1 tag. I suggest deleting this file.

2022-04-29 00:11 UTC, ligiabernardet commented on README.md
> +git clone -b feature/global_workflow https://github.com/jkbk2004/ufs-mrweather-app
It seems this should not point to someone's fork. The user should clone the master branch of the ufs-mrweather-app

2022-04-29 12:09 UTC, jkbk2004 commented on README.md
> +git clone -b feature/global_workflow https://github.com/jkbk2004/ufs-mrweather-app
@ligiabernardet corrected the url

2022-04-29 16:15 UTC, ligiabernardet approved these changes

2022-05-04 15:11 UTC, merged